/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AmountCard: typeof import('./components/AmountCard.vue')['default']
    AmountCardWithBackground: typeof import('./components/AmountCardWithBackground.vue')['default']
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppDrawer: typeof import('./components/AppDrawer.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppWrapper: typeof import('./components/AppWrapper.vue')['default']
    BarChartCard: typeof import('./components/BarChartCard.vue')['default']
    BarChartHorizontalCard: typeof import('./components/BarChartHorizontalCard.vue')['default']
    CardWithTitle: typeof import('./components/CardWithTitle.vue')['default']
    CardWithTitleImage: typeof import('./components/CardWithTitleImage.vue')['default']
    ChipDiff: typeof import('./components/ChipDiff.vue')['default']
    ContainerAndTruckUtilizationPage: typeof import('./components/ContainerAndTruckUtilizationPage.vue')['default']
    DailyPage: typeof import('./components/DailyPage.vue')['default']
    DocumentCard: typeof import('./components/DocumentCard.vue')['default']
    DocumentPage: typeof import('./components/DocumentPage.vue')['default']
    FinancialPage: typeof import('./components/FinancialPage.vue')['default']
    KpiCard: typeof import('./components/KpiCard.vue')['default']
    KpiPage: typeof import('./components/KpiPage.vue')['default']
    LoginCard: typeof import('./components/LoginCard.vue')['default']
    MonthlyBarChart: typeof import('./components/MonthlyBarChart.vue')['default']
    MonthlyPage: typeof import('./components/MonthlyPage.vue')['default']
    NavigationTabs: typeof import('./components/NavigationTabs.vue')['default']
    OperationAndSafetyPage: typeof import('./components/OperationAndSafetyPage.vue')['default']
    OperationCard: typeof import('./components/OperationCard.vue')['default']
    OutboundPresentCard: typeof import('./components/OutboundPresentCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadPage: typeof import('./components/UploadPage.vue')['default']
    WaterConsumptionCard: typeof import('./components/WaterConsumptionCard.vue')['default']
    WorkerCard: typeof import('./components/WorkerCard.vue')['default']
  }
}
