/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/3pl/daily': RouteRecordInfo<'/3pl/daily', '/3pl/daily', Record<never, never>, Record<never, never>>,
    '/3pl/financial': RouteRecordInfo<'/3pl/financial', '/3pl/financial', Record<never, never>, Record<never, never>>,
    '/3pl/kpi': RouteRecordInfo<'/3pl/kpi', '/3pl/kpi', Record<never, never>, Record<never, never>>,
    '/3pl/monthly': RouteRecordInfo<'/3pl/monthly', '/3pl/monthly', Record<never, never>, Record<never, never>>,
    '/3pl/operation-and-safety': RouteRecordInfo<'/3pl/operation-and-safety', '/3pl/operation-and-safety', Record<never, never>, Record<never, never>>,
    '/3pl-ptfi-bak/daily': RouteRecordInfo<'/3pl-ptfi-bak/daily', '/3pl-ptfi-bak/daily', Record<never, never>, Record<never, never>>,
    '/3pl-ptfi-bak/financial': RouteRecordInfo<'/3pl-ptfi-bak/financial', '/3pl-ptfi-bak/financial', Record<never, never>, Record<never, never>>,
    '/3pl-ptfi-bak/kpi': RouteRecordInfo<'/3pl-ptfi-bak/kpi', '/3pl-ptfi-bak/kpi', Record<never, never>, Record<never, never>>,
    '/3pl-ptfi-bak/monthly': RouteRecordInfo<'/3pl-ptfi-bak/monthly', '/3pl-ptfi-bak/monthly', Record<never, never>, Record<never, never>>,
    '/3pl-ptfi-bak/operation-and-safety': RouteRecordInfo<'/3pl-ptfi-bak/operation-and-safety', '/3pl-ptfi-bak/operation-and-safety', Record<never, never>, Record<never, never>>,
    '/ff/cargo-and-delivery-performance': RouteRecordInfo<'/ff/cargo-and-delivery-performance', '/ff/cargo-and-delivery-performance', Record<never, never>, Record<never, never>>,
    '/ff/container-and-truck-utilization': RouteRecordInfo<'/ff/container-and-truck-utilization', '/ff/container-and-truck-utilization', Record<never, never>, Record<never, never>>,
    '/ff/documents': RouteRecordInfo<'/ff/documents', '/ff/documents', Record<never, never>, Record<never, never>>,
    '/ff/kpi': RouteRecordInfo<'/ff/kpi', '/ff/kpi', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/ptfiDaily': RouteRecordInfo<'/ptfiDaily', '/ptfiDaily', Record<never, never>, Record<never, never>>,
    '/ptfiFinancial': RouteRecordInfo<'/ptfiFinancial', '/ptfiFinancial', Record<never, never>, Record<never, never>>,
    '/ptfiKpi': RouteRecordInfo<'/ptfiKpi', '/ptfiKpi', Record<never, never>, Record<never, never>>,
    '/ptfiMonthly': RouteRecordInfo<'/ptfiMonthly', '/ptfiMonthly', Record<never, never>, Record<never, never>>,
    '/ptfiOperationSafety': RouteRecordInfo<'/ptfiOperationSafety', '/ptfiOperationSafety', Record<never, never>, Record<never, never>>,
    '/upload/forklift': RouteRecordInfo<'/upload/forklift', '/upload/forklift', Record<never, never>, Record<never, never>>,
    '/upload/kpi': RouteRecordInfo<'/upload/kpi', '/upload/kpi', Record<never, never>, Record<never, never>>,
    '/upload/manpower': RouteRecordInfo<'/upload/manpower', '/upload/manpower', Record<never, never>, Record<never, never>>,
    '/upload/shipmentbyproduct': RouteRecordInfo<'/upload/shipmentbyproduct', '/upload/shipmentbyproduct', Record<never, never>, Record<never, never>>,
    '/upload/water': RouteRecordInfo<'/upload/water', '/upload/water', Record<never, never>, Record<never, never>>,
  }
}
