/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/ptfiDaily': RouteRecordInfo<'/ptfiDaily', '/ptfiDaily', Record<never, never>, Record<never, never>>,
    '/ptfiDailyCc': RouteRecordInfo<'/ptfiDailyCc', '/ptfiDailyCc', Record<never, never>, Record<never, never>>,
    '/ptfiDailyRp': RouteRecordInfo<'/ptfiDailyRp', '/ptfiDailyRp', Record<never, never>, Record<never, never>>,
    '/ptfiFinancial': RouteRecordInfo<'/ptfiFinancial', '/ptfiFinancial', Record<never, never>, Record<never, never>>,
    '/ptfiKpi': RouteRecordInfo<'/ptfiKpi', '/ptfiKpi', Record<never, never>, Record<never, never>>,
    '/ptfiMonthly': RouteRecordInfo<'/ptfiMonthly', '/ptfiMonthly', Record<never, never>, Record<never, never>>,
    '/ptfiOperationSafety': RouteRecordInfo<'/ptfiOperationSafety', '/ptfiOperationSafety', Record<never, never>, Record<never, never>>,
  }
}
